# Generated by Django 3.2 on 2022-04-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200211_1303'),
        ('products', '0003_auto_20220317_1733'),
    ]

    operations = [
    ]
